config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :viewers
  resources :home
  resources :messages, only: [:create]
  resources :contracts
  resources :prices
  resources :cloths
  resources :accessories
  resources :google, only: [:index, :create]
  resources :photographers, only: [:index, :show, :update, :edit]
  resources :contract_photographers, only: [:edit]
  resources :signatures, only: [:index, :create]
  resources :schedule, only: [:index]
  resources :raws, only: [:show, :create, :index]
  put 'photographers/:id/payall' => 'photographers#payall', :as => :payall_photo
  get '/articles/:id/:title' => 'articles#show', :as => :article_with_title
  get '/posing' => 'articles#index', :as => :article_posing
  get '/concept' => 'articles#index', :as => :article_concept
  get '/clothes' => 'articles#index', :as => :article_clothes
  get '/ask' => 'articles#index', :as => :article_ask
  get '/scription/:id' => 'contracts#scription', :as => :contract_scription
  post '/raws/:id/submit' => 'raws#submit', :as => 'submit_raws'
  post "/upload_image" => "upload#upload_image", :as => :upload_image
  get "/download_file/:name" => "upload#access_file", :as => :access_file, :name => /.*/

  get '/api/viewers/:id' => 'viewers#showMobile', :as => :show_viewers_mobile
  get "/" => redirect("/home")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessory.rb
class Accessory < ApplicationRecord
end

app/models/admin_secret.rb
class AdminSecret < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :images 
  accepts_nested_attributes_for :images, :allow_destroy => true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :contract
  belongs_to :cloth, optional: true
  belongs_to :accessory, optional: true
end

app/models/cloth.rb
class Cloth < ApplicationRecord
end

app/models/contract.rb
class Contract < ApplicationRecord
  has_many :contract_plans
  has_many :contract_photographers
  has_many :viewers
  has_many :carts
  has_many :plus
  accepts_nested_attributes_for :contract_photographers, :allow_destroy => true
  accepts_nested_attributes_for :plus, :allow_destroy => true
  accepts_nested_attributes_for :contract_plans, :allow_destroy => true
  accepts_nested_attributes_for :carts, :allow_destroy => true
  accepts_nested_attributes_for :viewers, :allow_destroy => true
  belongs_to :price, optional: true
  mount_uploader :sign, SignUploader
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :name, PhotosUploader
  belongs_to :article
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/package.rb
class Package < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :photo, PhotosUploader
end

app/models/photographer.rb
class Photographer < ApplicationRecord
  has_many :contract_photographers
  mount_uploader :avatar, AvatarUploader
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :viewer
end

app/models/plu.rb
class Plu < ApplicationRecord
  belongs_to :contract
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/video.rb
class Video < ApplicationRecord
end

app/models/viewer.rb
class Viewer < ApplicationRecord
  belongs_to :contract
  has_many :pictures
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  require 'net/http'
  
  def index
    if request.path == '/posing'
      @articles = Article.all.where(kind: 1)
      @article = Article.find_by(kind: 1, favorite: 1)
      @articles_rand= Article.order("RAND()").limit(6)
    elsif request.path == '/clothes'
      @articles = Article.all.where(kind: 0)
      @article = Article.find_by(kind: 0, favorite: 1)
      @articles_rand = Article.order("RAND()").limit(6)
    elsif request.path == '/ask'
      @articles = Article.all.where(kind: 3)
      @article = Article.find_by(kind: 3, favorite: 1)
      @articles_rand= Article.order("RAND()").limit(6)
    elsif request.path == '/concept'
      @articles = Article.all.where(kind: 2)
      @article = Article.find_by(kind: 2, favorite: 1)
      @articles_rand= Article.order("RAND()").limit(6)
    else 
      @articles = Article.all
    end
  end

  def show
    @article = Article.find(params[:id])
    @articles_rand = Article.order("RAND()")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plus_helper.rb
module PlusHelper
end

app/helpers/raws_helper.rb
module RawsHelper
end

app/views/articles/index.html.erb
<div id="wrapper">
	<% if @articles && @article && @articles_rand%>
		<div id="main">
			<div class="inner">
				<hr style="border-bottom: solid 10px #f56a6a;" >
				<div>
					<a class="sub-nav-bar-article" href="<%= cloths_path%>">Truy cập bảng giá thuê trang phục </a>
					<a class="sub-nav-bar-article" href="<%= accessories_path%>">Truy cập bảng giá mua phụ kiện </a>
					<a class="sub-nav-bar-article" href="<%= prices_path%>">Truy cập bảng giá dịch vụ</a>
				</div>
				<section id="banner">
					<div class="content">
						<header>
							<a href="<%= article_with_title_path(@article, :title => @article.url) %>">
								<h1><%=@article.title%></h1>
							</a>
							<p>by the Classic Studio</p>
						</header>
						<p><%=@article.description[0..700]%></p>
						<ul class="actions">
						</ul>
					</div>
					<a class="image object" href="<%= article_with_title_path(@article, :title => @article.url) %>">
						<img src="<%=@article.images[0].name%>" alt="" />
					</a>
				</section>
				<section>
					<header class="major">
						<h2>Nội dung chúng tôi có:</h2>
					</header>
					<div class="posts">
						<% @articles.each do |article| %>
							<article>
								<% if article.images[0]%>
									<a class="image object" href="<%= article_with_title_path(article, :title => article.url) %>"><div class="image"><img src="<%=article.images[0].name %>" alt="costume"/></div></a>
								<% end %>
								<a href="<%= article_with_title_path(article, :title => article.url) %>">
									<h3><%=article.title %></h3>
								</a>
								<p><%=article.description[0..200] %></p>
								<ul class="actions">
								</ul>
							</article>
						<% end %>
					</div>
				</section>
			</div>
		</div>
		<div id="sidebar">
			<div class="inner">
				<nav id="menu">
					<header class="major">
						<h2>Menu</h2>
					</header>
					<ul>
						<li><a href="/clothes">Clothes (Trang phục)</a></li>
						<li><a href="/posing">Posing (Tạo dáng)</a></li>
						<li><a href="/concept">Concept (Chủ đề)</a></li>
						<li><a href="/ask">Ask & Answer (Hỏi đáp)</a></li>
					</ul>
				</nav>
				<section>
					<header class="major">
						<h2>Bài viết liên quan</h2>
					</header>
					<div class="mini-posts">
					<% @articles_rand.each do |art| %>
						<article>
							<a class="image" href="<%= article_with_title_path(art, :title => art.url) %>">
								<% if art.images[0] %>
									<img src="<%= art.images[0].name %>" alt="" />
								<% end %>
							</a>
							<a href="<%= article_with_title_path(art, :title => art.url) %>">
								<p><%= art.title %></p>
							</a>
						</article>
						<% end %>
					</div>
					<ul class="actions">
					</ul>
				</section>
				<section>
					<div class="fb-page" data-href="https://www.facebook.com/classic.yearbook/" data-height="1500" data-tabs="timeline,events" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/classic.yearbook/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/classic.yearbook/">The Classic Studio - Kỷ yếu số 1 Đà Thành</a></blockquote></div>
				</section>
			</div>
		</div>
	<% else %>
		<h2>Nothing here</h2>
	<% end %>
</div>

app/views/articles/show.html.erb
<div id="wrapper">
	<% if @article%>
		<div id="main">
			<div class="inner">
				<hr style="border-bottom: solid 10px #f56a6a;" >
				<% if @article.kind == 0 %>
					<% url = request.path %>
					<% cloth = Cloth.find_by(link: url) %>
					<% if cloth %>
						<a href="<%= cloth_path(cloth)%>">Truy cập bảng giá thuê trang phục <%=@article.title%> </a>
					<% end %>
				<% end %>
				<section id="banner">
					<div class="content">
						<header>
							<a href="<%= article_with_title_path(@article, :title => @article.url) %>">
								<h1><%=@article.title%></h1>
							</a>
							<p>by the Classic Studio</p>
						</header>
						<div class="fb-like" data-href="<%= request.original_url %>" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
            <hr>
						<div class="grid-css grid-css--grid" data-col-lg="5" data-col-md="2" data-col-sm="2" data-col-xs="1" data-gap="30">
              <div class="grid__inner">
                <div class="grid-sizer"></div>
                <% @article.images.each do |image| %>
                  <div class="grid-item normal">
                    <div class="grid-item__inner">  
                      <div class="grid-item__content-wrapper">
                        <div class="portfolio" href= "<%= image.name %>"><a class="portfolio__bg" href= "<%= image.name %>" style="background-image: url('<%= image.name %>');" data-effect="mfp-zoom-in"><img src="<%= image.name %>"/></a>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
						<p class="art-desc"><%=@article.description%></p>
            <div id="myDiv">
            </div>
						<hr>
						<div class="fb-like" data-href="<%= request.original_url %>" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
						<div class="fb-comments" data-href="<%= request.original_url %>" data-numposts="10" data-mobile="false" data-width="100%"></div>
					</div>
				</section>
			</div>
		</div>
		<div id="sidebar">
			<div class="inner">
				<nav id="menu">
					<header class="major">
						<h2>Menu</h2>
					</header>
					<ul>
						<li><a href="/clothes">Clothes (Trang phục)</a></li>
						<li><a href="/posing">Posing (Tạo dáng)</a></li>
						<li><a href="/concept">Concept (Chủ đề)</a></li>
						<li><a href="/ask">Ask & Answer (Hỏi đáp)</a></li>
					</ul>
				</nav>
				<section>
					<header class="major">
						<h2>Bài viết liên quan</h2>
					</header>
					<div class="mini-posts">
					<% @articles_rand.each do |art| %>
						<article>
							<a class="image" href="<%= article_with_title_path(art, :title => art.url) %>">
								<% if art.images[0] %>
									<img src="<%= art.images[0].name %>" alt="" />
								<% end %>
							</a>
							<a href="<%= article_with_title_path(art, :title => art.url) %>">
								<p><%= art.title %></p>
							</a>
						</article>
						<% end %>
					</div>
					<ul class="actions">
					</ul>
				</section>
				<section>
					<div class="fb-page" data-href="https://www.facebook.com/classic.yearbook/" data-height="1500" data-width="250" data-tabs="timeline,events" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/classic.yearbook/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/classic.yearbook/">The Classic Studio - Kỷ yếu số 1 Đà Thành</a></blockquote></div>
				</section>
			</div>
		</div>
	<% else %>
		<h2>Nothing here</h2>
	<% end %>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    var xmlString = <%= @article.content.to_json.to_s.html_safe %>;
    var div = document.getElementById('myDiv');
    $('#myDiv').html(xmlString);
		$("p:has(img)").css({textAlign: "center"});
  })
</script>