config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :viewers
  resources :home
  resources :messages, only: [:create]
  resources :contracts
  resources :prices
  resources :cloths
  resources :accessories
  resources :google, only: [:index, :create]
  resources :photographers, only: [:index, :show, :update, :edit]
  resources :contract_photographers, only: [:edit]
  resources :signatures, only: [:index, :create]
  resources :schedule, only: [:index]
  resources :raws, only: [:show, :create, :index]
  put 'photographers/:id/payall' => 'photographers#payall', :as => :payall_photo
  get '/articles/:id/:title' => 'articles#show', :as => :article_with_title
  get '/posing' => 'articles#index', :as => :article_posing
  get '/concept' => 'articles#index', :as => :article_concept
  get '/clothes' => 'articles#index', :as => :article_clothes
  get '/ask' => 'articles#index', :as => :article_ask
  get '/scription/:id' => 'contracts#scription', :as => :contract_scription
  post '/raws/:id/submit' => 'raws#submit', :as => 'submit_raws'
  post "/upload_image" => "upload#upload_image", :as => :upload_image
  get "/download_file/:name" => "upload#access_file", :as => :access_file, :name => /.*/

  get '/api/viewers/:id' => 'viewers#showMobile', :as => :show_viewers_mobile
  get "/" => redirect("/home")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessory.rb
class Accessory < ApplicationRecord
end

app/models/admin_secret.rb
class AdminSecret < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :images 
  accepts_nested_attributes_for :images, :allow_destroy => true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :contract
  belongs_to :cloth, optional: true
  belongs_to :accessory, optional: true
end

app/models/cloth.rb
class Cloth < ApplicationRecord
end

app/models/contract.rb
class Contract < ApplicationRecord
  has_many :contract_plans
  has_many :contract_photographers
  has_many :viewers
  has_many :carts
  has_many :plus
  accepts_nested_attributes_for :contract_photographers, :allow_destroy => true
  accepts_nested_attributes_for :plus, :allow_destroy => true
  accepts_nested_attributes_for :contract_plans, :allow_destroy => true
  accepts_nested_attributes_for :carts, :allow_destroy => true
  accepts_nested_attributes_for :viewers, :allow_destroy => true
  belongs_to :price, optional: true
  mount_uploader :sign, SignUploader
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :name, PhotosUploader
  belongs_to :article
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/package.rb
class Package < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :photo, PhotosUploader
end

app/models/photographer.rb
class Photographer < ApplicationRecord
  has_many :contract_photographers
  mount_uploader :avatar, AvatarUploader
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :viewer
end

app/models/plu.rb
class Plu < ApplicationRecord
  belongs_to :contract
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/video.rb
class Video < ApplicationRecord
end

app/models/viewer.rb
class Viewer < ApplicationRecord
  belongs_to :contract
  has_many :pictures
end

app/controllers/viewers_controller.rb
class ViewersController < ApplicationController
  def index
    # @image = Cloudinary::Api.resources(:type => :upload, :prefix => "50mmstudio")
  end

  def create 
    if params[:code]
      redirect_to viewer_path(params[:code])
    else
      redirect_to viewers_path
    end
  end

  def show
    @view = Contract.find_by(code: params[:id].downcase)
    if params[:page]
      @page = params[:page]
    else 
      @page = 1
    end
    if @view
      @link = @view.viewers.where(typeFile: 1)[0].drive_link.split(',')
    else
      redirect_to viewers_path
      flash[:alert] = 'Maybe your photos are not completed or invalid!'
    end
  end

  def showMobile
    ctr = Contract.find_by(code: params[:id].downcase)
    # if params[:page]
    #   @page = params[:page]
    # else 
    #   @page = 1
    # end
    if ctr
      view = ctr.viewers.where(typeFile: 1)[0]
      pics = Picture.where(viewer_id: view.id)
      binding.pry
      return render json: pics
    else
      return render json: { error: 'Cannot find!' }
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plus_helper.rb
module PlusHelper
end

app/helpers/raws_helper.rb
module RawsHelper
end

app/helpers/viewers_helper.rb
module ViewersHelper
end

app/views/viewers/index.html.erb
<!-- Intro -->
<%= javascript_include_tag 'rawui', 'data-turbolinks-track' => true %>
<div style="overflow:hidden">
  <section id="intro" class="main style1 dark fullscreen">
    <div class="content">
      <header>
        <h2 style="color: white;">Xin chào!</h2>
      </header>
      <p>Chào mừng bạn đến với <strong>kho hình ảnh</strong> của chúng tôi. <br>Với mã code được cấp, bạn có thể truy cập ẢNH PHOTOSHOP hoặc ẢNH GỐC trong hệ thống.
        <br>Bạn cũng có thể trải nghiệm chức năng lựa ảnh online với <strong>RAW FILTER </strong>.
      <footer>
        <a href="#one" class="button style2 down">More</a>
      </footer>
    </div>
  </section>
<!-- One -->
  <section id="one" class="main style2 right dark fullscreen">
    <div class="content box style2">
      <header>
        <h2>Photoshop albums?</h2>
      </header>
      <p>Nếu tìm kiếm album ảnh đã chỉnh sửa thì hãy nhập mã code vào ô bên dưới và submit để kiểm tra nhé.</p>
      <%= form_tag(viewers_path, method: :post) do %>
        <input type="text" name="code">
        <%= submit_tag "Submit", class: 'btn btn-primary btn-submit' %>
      <% end %>
    </div>
    <a href="#two" class="button style2 down anchored">Next</a>
  </section>
<!-- Two -->
  <section id="two" class="main style2 left dark fullscreen">
    <div class="content box style2">
      <header>
        <h2>RAW FILTER?</h2>
      </header>
      <p>Đây là hệ thống lọc hình ảnh gốc, những hình bạn chọn sẽ được chúng tôi edit, bạn cũng có thể xem và download hình.</p>
      <%= form_tag(raws_path, method: :post) do %>
        <input type="text" name="code">
        <%= submit_tag "Submit", class: 'btn btn-primary btn-submit' %>
      <% end %>
    </div>
  </section>
</div> 

app/views/viewers/show.html.erb
<div class="container">
  <section class="md-section photo-section" id="id-7">
    <div class="info-view">
      <h2>Picture</h2>
      <h3 style="text-transform: uppercase"><%=@view.group%> - <%=@view.school%></h3>
      <p style="text-transform: uppercase"><%=@view.school_year%></p>
      <% @link.each_index do |index| %>
        <% count = index + 1 %>
        <% if index + 1 == @page.to_i %>
          <%= link_to index + 1, viewer_path(@view.code, :page => count), class: 'paginate active-pag' %>
        <% else %>
          <%= link_to index + 1, viewer_path(@view.code, :page => count), class: 'paginate' %>
        <% end %>
      <% end %>
    </div>
    <% id = @page.to_i - 1 %>
    <% picture = @view.viewers.first.pictures.where(folder: @link[id])[0]%>
    <p style="margin: 0 auto">Thư mục này có <b><%=picture.pictureId.split(',').length%></b> tấm</p>
    <div class="container">
      <div class="col-sm-12">
        <div class="grid-css grid-css--grid" data-col-lg="6" data-col-md="6" data-col-sm="6" data-col-xs="1" data-gap="30">
          <div class="grid__inner">
            <div class="grid-sizer"></div>
            <% picture.pictureId.split(',').each_with_index do |pic, index| %>
              <div class="grid-item normal">
                <div class="grid-item__inner">  
                  <div class="grid-item__content-wrapper">
                    <% urlparse = "https://drive.google.com/thumbnail?id=#{pic}&sz=w300-h300"%>
                    <% urlparseHD = "https://drive.google.com/thumbnail?id=#{pic}&sz=w2048-h1365"%>
                    <div class="portfolio" href="<%= urlparseHD %>" id = "<%= index %>" >
                      <a class="portfolio__bg" href= "<%= urlparseHD %>" style="background-image: url('<%= urlparse %>');" data-effect="mfp-zoom-in">
                        <img src="" id="main_viewer" alt="classic_pictures">
                      </a>
                    </div>
                  </div>
                </div>
                <% urlparseFullHD = "https://drive.google.com/uc?export=view&id=#{pic}"%>
                <p style="text-align: center"><%= picture.name.split(',')[index] %> 
                  <a href="<%= urlparseFullHD %>" download>
                    <i class="fa fa-arrow-circle-down"></i>
                  </a>
                </p>
                <hr>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
<div class="top-menu-quick">
  <div id="back-to-top"><i class="pe-7s-angle-up"></i></div>
</div>
<script>
  $(document).ready(function(){
    $(".portfolio").click(function(event) {
      var url_string1 = $(this).attr('href');
      var url1 = new URL(url_string1);
      var c1 = url1.searchParams.get("id");
      const urlparseFullHD1 = `https://drive.google.com/uc?export=view&id=${c1}`;
      var images = <%= picture.pictureId.split(',').to_json.to_s.html_safe %>;
      var btn_prev = $(`<button class="prev"><i class="fa fa-angle-left"></i></button>`);
      var btn_next = $(`<button class="next"><i class="fa fa-angle-right"></i></button>`);
      var download_btn = $(`<a id="downloadBtn" href="${urlparseFullHD1}" download><i class="fa fa-arrow-circle-down"></i></a>`);
      btn_prev.click(function(event){
        var url_string = $(".mfp-img").attr('src'); //window.location.href
        var url = new URL(url_string);
        var c = url.searchParams.get("id");
        const currentIndex = images.indexOf(c);
        prev = images[currentIndex - 1];
        urlparseHD = `https://drive.google.com/thumbnail?id=${prev}&sz=w2048-h1365`;
        urlparseFullHD = `https://drive.google.com/uc?export=view&id=${prev}`;
        $(".mfp-img").attr('src', urlparseHD);
        $("#downloadBtn").attr('href', urlparseFullHD);
        event.stopImmediatePropagation();
      });
      btn_next.click(function(event){
        var url_string = $(".mfp-img").attr('src'); //window.location.href
        var url = new URL(url_string);
        var c = url.searchParams.get("id");
        const currentIndex = images.indexOf(c);
        next = images[currentIndex + 1];
        urlparseHD = `https://drive.google.com/thumbnail?id=${next}&sz=w2048-h1365`;
        urlparseFullHD = `https://drive.google.com/uc?export=view&id=${next}`;
        $(".mfp-img").attr('src', urlparseHD);
        $("#downloadBtn").attr('href', urlparseFullHD);
        event.stopImmediatePropagation();
      });
      download_btn.click(function(event){
        event.stopImmediatePropagation();
      })
      $(".mfp-container").append(btn_prev, btn_next, download_btn);
    });
    $("top-menu-quick").click(function(){
      window.scrollTo(0, 0);
    });
  });
</script>