config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :viewers
  resources :home
  resources :messages, only: [:create]
  resources :contracts
  resources :prices
  resources :cloths
  resources :accessories
  resources :google, only: [:index, :create]
  resources :photographers, only: [:index, :show, :update, :edit]
  resources :contract_photographers, only: [:edit]
  resources :signatures, only: [:index, :create]
  resources :schedule, only: [:index]
  resources :raws, only: [:show, :create, :index]
  put 'photographers/:id/payall' => 'photographers#payall', :as => :payall_photo
  get '/articles/:id/:title' => 'articles#show', :as => :article_with_title
  get '/posing' => 'articles#index', :as => :article_posing
  get '/concept' => 'articles#index', :as => :article_concept
  get '/clothes' => 'articles#index', :as => :article_clothes
  get '/ask' => 'articles#index', :as => :article_ask
  get '/scription/:id' => 'contracts#scription', :as => :contract_scription
  post '/raws/:id/submit' => 'raws#submit', :as => 'submit_raws'
  post "/upload_image" => "upload#upload_image", :as => :upload_image
  get "/download_file/:name" => "upload#access_file", :as => :access_file, :name => /.*/

  get '/api/viewers/:id' => 'viewers#showMobile', :as => :show_viewers_mobile
  get "/" => redirect("/home")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessory.rb
class Accessory < ApplicationRecord
end

app/models/admin_secret.rb
class AdminSecret < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :images 
  accepts_nested_attributes_for :images, :allow_destroy => true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :contract
  belongs_to :cloth, optional: true
  belongs_to :accessory, optional: true
end

app/models/cloth.rb
class Cloth < ApplicationRecord
end

app/models/contract.rb
class Contract < ApplicationRecord
  has_many :contract_plans
  has_many :contract_photographers
  has_many :viewers
  has_many :carts
  has_many :plus
  accepts_nested_attributes_for :contract_photographers, :allow_destroy => true
  accepts_nested_attributes_for :plus, :allow_destroy => true
  accepts_nested_attributes_for :contract_plans, :allow_destroy => true
  accepts_nested_attributes_for :carts, :allow_destroy => true
  accepts_nested_attributes_for :viewers, :allow_destroy => true
  belongs_to :price, optional: true
  mount_uploader :sign, SignUploader
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :name, PhotosUploader
  belongs_to :article
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/package.rb
class Package < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :photo, PhotosUploader
end

app/models/photographer.rb
class Photographer < ApplicationRecord
  has_many :contract_photographers
  mount_uploader :avatar, AvatarUploader
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :viewer
end

app/models/plu.rb
class Plu < ApplicationRecord
  belongs_to :contract
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/video.rb
class Video < ApplicationRecord
end

app/models/viewer.rb
class Viewer < ApplicationRecord
  belongs_to :contract
  has_many :pictures
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @images = Photo.all
    @videos = Video.all
    @message = Message.new
    @photographers = Photographer.where(favorite: true).limit(3)
  end

  def create
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plus_helper.rb
module PlusHelper
end

app/helpers/raws_helper.rb
module RawsHelper
end

app/views/home/index.html.erb
<div class="page-wrap">
	<!-- Content-->
	<div class="md-content">
		<!-- hero -->
		<div class="hero" id="id-1" style="background-image: url('img/bg/1.jpg');">
			<div class="hero__wrapper">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 ">
							<h1 class="hero__title">
								<!-- typing__module -->
								<div class="typing__module" data-options='{"typeSpeed":60}'>
									<div class="typed-strings"><span>The classic studio</span><span>We are photographers</span><span>We are creative</span>
									</div><span class="typed"></span>
								</div><!-- End / typing__module -->
							</h1>
							<p class="hero__text" style="font-size:15px">The classic studio works in yearbook, event, wedding projects<br>
								Contact: (+84)1223420210
							</p>
						</div>
					</div><span id="back-to-down"><i class="pe-7s-angle-down"></i></span>
				</div>
			</div>
		</div><!-- End / hero -->
		<!-- Section -->
		<section class="md-section bg-gray" id="id-2">
			<div class="container">
				<div class="row">
					<div class="col-lg-4">
						<!-- slide-image -->
						<div class="slide-image">
							<!-- swiper__module swiper-container -->
							<div class="swiper__module swiper-container slide-image__front" data-options='{"slidesPerView":1,"spaceBetween":0}'>
								<div class="swiper-wrapper">
									<div class="slide-item" style="background-image: url('img/about/1.jpg');"></div>
									<div class="slide-item" style="background-image: url('img/about/2.jpg');"></div>
									<div class="slide-item" style="background-image: url('img/about/3.jpg');"></div>
								</div>
								<div class="swiper-pagination-custom"></div>
							</div><!-- End / swiper__module swiper-container -->
							<!-- swiper-thumbnails__module swiper-container -->
							<div class="swiper-thumbnails__module swiper-container slide-image__black" data-options='{"slidesPerView":1,"spaceBetween":0,"delay":10000}'>
								<div class="swiper-wrapper">
									<div class="slide-item" style="background-image: url('img/about/1b.jpg');"></div>
									<div class="slide-item" style="background-image: url('img/about/2b.jpg');"></div>
									<div class="slide-item" style="background-image: url('img/about/3b.jpg');"></div>
								</div>
							</div><!-- End / swiper-thumbnails__module swiper-container -->
						</div><!-- End / slide-image -->
					</div>
					<div class="col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-1 ">
						<!-- title -->
						<div class="title">
							<h2 class="title__title">Hello from The classic studio</h2><h5>Quan Do</h5>
						</div><!-- End / title -->
						<p class="fz-16">
							"<b>Classic Studio</b> was established in <b>2013</b>, formerly known as Elysium Production, has been renamed many times and developing to be one of the <b>organisations of talented freelancers</b> in the field of <b>image services</b> in Da Nang, Vietnam. Although we are established and operating not in a very long time, we believe that we are improving to bring <b>better and better quality service</b> to customers who come with us and believe in us."<br>
						</p>
					</div>
				</div>
				<!-- swiper__module swiper-container -->
				<div class="swiper__module swiper-container mt-50" data-options='{"slidesPerView":3,"spaceBetween":30,"autoplay":2000,"breakpoints":{"640":{"slidesPerView":1},"991":{"slidesPerView":2}}}'>
					<div class="swiper-wrapper">
						<!-- service -->
						<div class="service mb-0">
							<div class="service__icon"><i class="pe-7s-paint-bucket"></i></div>
							<h3 class="service__title">Social Media</h3>
							<p class="service__text">Suspendisse ac elit vitae est lacinia interdum eu sit amet mauris. Phasellus</p>
						</div><!-- End / service -->
						<!-- service -->
						<div class="service mb-0">
							<div class="service__icon"><i class="pe-7s-paint-bucket"></i></div>
							<h3 class="service__title">Social Media</h3>
							<p class="service__text">Integer placerat ullamcorper urna nec rhoncus. Sed velit justo, lacinia non</p>
						</div><!-- End / service -->
						<!-- service -->
						<div class="service mb-0">
							<div class="service__icon"><i class="pe-7s-lintern"></i></div>
							<h3 class="service__title">Investment Planning</h3>
							<p class="service__text">Mauris lacinia venenatis dolor sit amet viverra. Integer malesuada nulla neque.</p>
						</div><!-- End / service -->
						<!-- service -->
						<div class="service mb-0">
							<div class="service__icon"><i class="pe-7s-gleam"></i></div>
							<h3 class="service__title">Risk Management</h3>
							<p class="service__text">Curabitur elementum urna augue, eu porta purus gravida in. Cras consectetur,</p>
						</div><!-- End / service -->
						<!-- service -->
						<div class="service mb-0">
							<div class="service__icon"><i class="pe-7s-anchor"></i></div>
							<h3 class="service__title">Marketing Planning</h3>
							<p class="service__text">Duis porttitor libero ac egestas euismod. Maecenas quis felis turpis. Nulla quis</p>
						</div><!-- End / service -->
						<!-- service -->
						<div class="service mb-0">
							<div class="service__icon"><i class="pe-7s-refresh"></i></div>
							<h3 class="service__title">Site Security</h3>
							<p class="service__text">Etiam non varius justo, vel tempor mi. Nulla facilisi. Fusce at tortor arcu.</p>
						</div><!-- End / service -->
						<!-- service -->
						<div class="service mb-0">
							<div class="service__icon"><i class="pe-7s-joy"></i></div>
							<h3 class="service__title">Risk Management</h3>
							<p class="service__text">Integer placerat ullamcorper urna nec rhoncus. Sed velit justo, lacinia non</p>
						</div><!-- End / service -->
						<!-- service -->
						<div class="service mb-0">
							<div class="service__icon"><i class="pe-7s-lock"></i></div>
							<h3 class="service__title">Investment Planning</h3>
							<p class="service__text">Mauris lacinia venenatis dolor sit amet viverra. Integer malesuada nulla neque.</p>
						</div><!-- End / service -->
						<!-- service -->
						<div class="service mb-0">
							<div class="service__icon"><i class="pe-7s-magnet"></i></div>
							<h3 class="service__title">Site Security</h3>
							<p class="service__text">Nam elit ligula, egestas et ornare non, viverra eu justo. Aliquam ornare lectus</p>
						</div><!-- End / service -->
					</div>
				</div><!-- End / swiper__module swiper-container -->
			</div>
		</section>
		<!-- End / Section -->
		<!-- Section -->
		<section class="md-section" id="id-3">
			<div class="container">
				<div class="row">
					<div class="col-lg-8 ">
						<!-- title -->
						<div class="title">
							<h2 class="title__title">portfolio</h2>
						</div><!-- End / title -->
					</div>
				</div>
				<div class="grid-css grid-css--grid" data-col-lg="3" data-col-md="2" data-col-sm="2" data-col-xs="1" data-gap="30">
					<div class="filter">
						<ul class="filter__list">
							<li><a href="#" data-filter="*">All</a></li>
							<li><a href="#" data-filter=".1">Yearbook</a></li>
							<li><a href="#" data-filter=".2">Night</a></li>
							<li><a href="#" data-filter=".3">Flycam</a></li>
							<li><a href="#" data-filter=".0">Video</a></li>
						</ul>
					</div>
					<div class="grid__inner">
						<div class="grid-sizer"></div>
						<% @videos.each do |video| %>
							<div class="grid-item normal <%=video.kind%>">
								<div class="grid-item__inner">
									<div class="grid-item__content-wrapper">
										<div class="portfolio fb-video" data-href="<%=video.video%>" data-width="500" data-height="500" data-show-text="false">
											<blockquote cite="<%=video.video%>" class="fb-xfbml-parse-ignore">
												<a class="portfolio__bg popup-video" href="<%=video.video%>" data-effect="mfp-zoom-in">READY FOR 18!</a>
												<p>Ảnh video kỷ yếu chất lượng chỉ có tại 50mm studio</p>
												Người đăng: <a href="https://www.facebook.com/classic.yearbook/">The Classic Studio - Kỷ yếu số 1 Đà Thành</a>
											</blockquote>
										</div>
									</div>
								</div>
							</div>
						<% end %>
						<% @images.each do |image| %>
							<div class="grid-item normal <%=image.kind%>">
								<div class="grid-item__inner">
									<div class="grid-item__content-wrapper">
										<!-- portfolio -->
										<div class="portfolio" href= "<%= image.photo %>"><a class="portfolio__bg" href= "<%= image.photo %>" style="background-image: url('<%= image.photo %>');" data-effect="mfp-zoom-in"><img src="<%= image.photo %>"/></a>
										</div><!-- End / portfolio -->
									</div>
								</div>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</section>
		<!-- End / Section -->
		<!-- Section -->
		<section class="md-section bg-gray" id="id-4">
			<div class="container">
				<div class="row">
					<div class="col-xs-12">
						<!-- title -->
						<div class="title">
							<h2 class="title__title">Our photographers</h2>
						</div><!-- End / title -->
					</div>
				</div>
				<div class="row">
					<% @photographers.each do |photo| %>
						<div class="col-lg-4">
							<div>
								<div class="post__media"><a href="#"><img src="<%=photo.avatar %>" alt=""/></a></div>
								<div class="post__body">
									<h2 class="post__title"><%=photo.name %></h2>
									<div class="post__meta"><span class="author"><a href="#"><%=photo.role %></a></span><span class="date">Jan 1, 2015</span></div>
									<p class="post__text"><%=photo.description %></p>
								</div>
							</div><!-- End /  -->
						</div>
					<% end %>
				</div>
			</div>
		</section>
		<section class="md-section" id="id-5">
			<div class="container">
				<div class="row">
					<div class="col-lg-4 ">
						<div class="title">
							<h2 class="title__title">Get in touch</h2>
						</div><!-- End / title -->
						<div class="mb-40">
							<div class="contact">
								<h3 class="contact__title">address</h3>
								<div>43 Tong Phuoc Pho St, Hai Chau Dist, Da Nang</div>
							</div><!-- End / contact -->
							<div class="contact">
								<h3 class="contact__title">email</h3>
								<div><a href="">dhquan1910@gmail.com</a></div>
							</div><!-- End / contact -->
							<div class="contact">
								<h3 class="contact__title">phone</h3>
								<div>+84 1223420210</div>
							</div><!-- End / contact -->
						</div>
					</div>
					<div class="col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-1 ">
						<div class="title">
							<h2 class="title__title">Or drop a message</h2>
						</div><!-- End / title -->
						<div class="form-wrapper">
							<!-- form-item -->
							<%= form_for @message, url: messages_path, html: {method: "post"} do |f| %>
								<div class="form-item form-item--half">
									<label class="form__label">email,<span>*</span>
									</label>
									<%= f.text_field :email, class: 'form-control'%>
								</div><!-- End / form-item -->
								<div class="form-item form-item--half">
									<label class="form__label">Name,<span>*</span>
									</label>
									<%= f.text_field :name, class: 'form-control'%>
								</div><!-- End / form-item -->
								<div class="form-item">
									<label class="form__label">message<span>*</span>
									</label>
									<%= f.text_area :message, class: 'form-control'%>
								</div><!-- End / form-item -->
								<div class="form-item">
									<%= f.submit 'Send message', class: 'md-btn btn-custom' %>
								</div><!-- End / form-item -->
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section class="md-section bg-gray" id="id-2">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-1 ">
						<!-- title -->
						<div class="title">
							<h2 class="title__title">FROM Co-Founder</h2><h5>Anh Nguyen</h5>
						</div><!-- End / title -->
						<p class="fz-16">
								"I am a kind of minimalism so I just want to focus on the moment of true love and feeling without any complex posing or acting. I believe there is a story in every photo. A simple hug, a smile or a teardrop make a lot of sense in the story. I am really enthusiastic in true feeling and love because they give me a lot of inspiration and emotion.
								<br>Come with us and we will be the best storyteller for your day. Your story will be kept in beautiful photos as the most precious memorabilia forever after."
						</p>
					</div>
					<div class="col-lg-4">
						<div class="slide-image">
							<div class="swiper__module swiper-container slide-image__front" data-options='{"slidesPerView":1,"spaceBetween":0}'>
								<div class="swiper-wrapper">
									<div class="slide-item" style="background-image: url('img/about/4.jpg');"></div>
									<div class="slide-item" style="background-image: url('img/about/4b.jpg');"></div>
									<div class="slide-item" style="background-image: url('img/about/3.jpg');"></div>
								</div>
								<div class="swiper-pagination-custom"></div>
							</div><!-- End / swiper__module swiper-container -->
							<div class="swiper-thumbnails__module swiper-container slide-image__black" data-options='{"slidesPerView":1,"spaceBetween":0,"delay":10000}'>
								<div class="swiper-wrapper">
									<div class="slide-item" style="background-image: url('img/about/5.jpg');"></div>
									<div class="slide-item" style="background-image: url('img/about/5b.jpg');"></div>
									<div class="slide-item" style="background-image: url('img/about/3b.jpg');"></div>
								</div>
							</div><!-- End / swiper-thumbnails__module swiper-container -->
						</div><!-- End / slide-image -->
					</div>
				</div>
			</div>
		</section>
	</div>
</div>