config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :viewers
  resources :home
  resources :messages, only: [:create]
  resources :contracts
  resources :prices
  resources :cloths
  resources :accessories
  resources :google, only: [:index, :create]
  resources :photographers, only: [:index, :show, :update, :edit]
  resources :contract_photographers, only: [:edit]
  resources :signatures, only: [:index, :create]
  resources :schedule, only: [:index]
  resources :raws, only: [:show, :create, :index]
  put 'photographers/:id/payall' => 'photographers#payall', :as => :payall_photo
  get '/articles/:id/:title' => 'articles#show', :as => :article_with_title
  get '/posing' => 'articles#index', :as => :article_posing
  get '/concept' => 'articles#index', :as => :article_concept
  get '/clothes' => 'articles#index', :as => :article_clothes
  get '/ask' => 'articles#index', :as => :article_ask
  get '/scription/:id' => 'contracts#scription', :as => :contract_scription
  post '/raws/:id/submit' => 'raws#submit', :as => 'submit_raws'
  post "/upload_image" => "upload#upload_image", :as => :upload_image
  get "/download_file/:name" => "upload#access_file", :as => :access_file, :name => /.*/

  get '/api/viewers/:id' => 'viewers#showMobile', :as => :show_viewers_mobile
  get "/" => redirect("/home")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessory.rb
class Accessory < ApplicationRecord
end

app/models/admin_secret.rb
class AdminSecret < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :images 
  accepts_nested_attributes_for :images, :allow_destroy => true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :contract
  belongs_to :cloth, optional: true
  belongs_to :accessory, optional: true
end

app/models/cloth.rb
class Cloth < ApplicationRecord
end

app/models/contract.rb
class Contract < ApplicationRecord
  has_many :contract_plans
  has_many :contract_photographers
  has_many :viewers
  has_many :carts
  has_many :plus
  accepts_nested_attributes_for :contract_photographers, :allow_destroy => true
  accepts_nested_attributes_for :plus, :allow_destroy => true
  accepts_nested_attributes_for :contract_plans, :allow_destroy => true
  accepts_nested_attributes_for :carts, :allow_destroy => true
  accepts_nested_attributes_for :viewers, :allow_destroy => true
  belongs_to :price, optional: true
  mount_uploader :sign, SignUploader
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :name, PhotosUploader
  belongs_to :article
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/package.rb
class Package < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :photo, PhotosUploader
end

app/models/photographer.rb
class Photographer < ApplicationRecord
  has_many :contract_photographers
  mount_uploader :avatar, AvatarUploader
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :viewer
end

app/models/plu.rb
class Plu < ApplicationRecord
  belongs_to :contract
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/video.rb
class Video < ApplicationRecord
end

app/models/viewer.rb
class Viewer < ApplicationRecord
  belongs_to :contract
  has_many :pictures
end

app/controllers/photographers_controller.rb
class PhotographersController < ApplicationController
  def index
    @photographers = Photographer.all
  end

  def show
    @photographer = Photographer.find(params[:id])
    uri   = URI.parse(request.fullpath)
    @status = ''
    @check = false
    if uri.query
      params = CGI.parse(uri.query)
      @status  = params['status'].first
      if @status == "unpaid"
        @shows = @photographer.contract_photographers.where(paid: false).joins(:contract).order('contracts.taken_date DESC')
      else
        @shows = @photographer.contract_photographers.joins(:contract).order('contracts.taken_date DESC')
      end
      token  = params['token'].first
      if AdminSecret.find_by(token_secret: token)
        @check = true
      end
    else
      @shows = @photographer.contract_photographers.joins(:contract).order('contracts.taken_date DESC')
    end
  end

  def update
    @photographer = ContractPhotographer.find(params[:id])
    if !@photographer.paid
      @photographer.update_attributes(paid: true)
    end
    redirect_to request.referrer, notice: "You're being redirected"
  end

  def payall
    @contract_pay = Photographer.find(params[:id]).contract_photographers
    @contract_pay.each do |pay|
      if !pay.paid
        pay.update_attributes(paid: true)
      end
    end
    redirect_to request.referrer, notice: "You're being redirected"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photographers_helper.rb
module PhotographersHelper
end

app/helpers/plus_helper.rb
module PlusHelper
end

app/helpers/raws_helper.rb
module RawsHelper
end

app/views/photographers/index.html.erb
<section class="md-section" id="id-8">
  <div class="row" style="padding: 0 2rem">
    <div class="container">
      <h3>Danh sách thợ</h3>
      <table>
        <tr>
          <th>Tên</th>
          <th>Số show đã nhận</th>
          <th>Số show cần thanh toán</th>
        </tr>
        <% @photographers.each do |p| %>
          <tr>
            <td>
              <a href="/photographers/<%=p.id%>">
                <%=p.name%>
              </a>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</section>

app/views/photographers/show.html.erb
<section class="md-section" id="id-8">
  <div class="row" style="padding: 0 2rem">
    <div class="container">
      <h3><%=@photographer.name%></h3>
      <div class="row">
        <div class="col-md-3">
          <img src="<%=@photographer.avatar%>">
          <div>
            <label>Họ và Tên: </label><b><%=@photographer.name %></b><br>
            <label>Vai trò: </label><b><%=@photographer.role%></b><br>
            <label>SĐT: </label><b><%=@photographer.phone%></b><br>
          </div>
        </div>
        <div class="col-md-9">
          <h4>Tính Lương</h4>
          <table>
            <tr>
              <th>Ngày</th>
              <th>Lớp - trường</th>
              <th>Gói mở rộng</th>
              <th>Vai trò</th>
              <th>Lương</th>
              <th>Ghi chú</th>
              <th>Thanh toán</th>
              <th>Edit</th>
            </tr>
               <% @shows.each do |p|%>
              <tr>
                <td>
                  <%=p.contract.taken_date%>
                </td>
                <td>
                  <%=p.contract.group%> - <%=p.contract.school%>
                </td>
                <td>
                  <% p.contract.package.split(',').each do |id|
                    pack = Package.find(id)
                    if pack %>
                      <span style="color: #a14617">
                      <%= '-' + pack.name %>
                      </span>
                    <% end
                  end %>
                </td>
                <td>
                  <%= p.role %>
                </td>
                <td>
                  <%= convert_money(p.salary) %>
                </td>
                <td>
                  <%= p.note %>
                </td>
                <% if p.paid %>
                  <td style="color: green">
                    Done
                  </td>
                <% else %>
                  <% if @check %>
                    <td style="color: red">
                      <%= link_to "Paid?", photographer_path(p.id), method: :put, class: 'paginate active-pag' %>
                    </td>
                    <td style="color: red">
                      <%= link_to "Edit?", edit_admin_contract_photographer_path(p.id), class: 'paginate active-pag', target: "_blank" %>
                    </td>
                  <% end%>
                <% end%>
              </tr>
            <% end %>
          </table>
          <span>Tổng tiền</span>
          <% if @shows.length == 0%>
            <h4>0</h4> 
          <% elsif @shows.length == 1%>
            <h4><%=convert_money(@shows[0].salary)%></h4> 
          <% else %>
            <h4><%=convert_money(@shows.map{|x| x.salary}.inject(:+))%></h4>
          <% end %>
          <% if @check %>
            <%= link_to "Pay all", payall_photo_path(@photographer), method: :put, class: 'paginate', data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>